---
- name: Update and install prerequisites
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker CE
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Download Docker Compose
  shell: curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Set permissions for Docker Compose
  file:
    path: /usr/local/bin/docker-compose
    mode: '0755'
    owner: root
    group: root

- name: Verify Docker Compose installation
  command: docker-compose --version
  register: docker_compose_version
  changed_when: false

- debug:
    msg: "Docker Compose version: {{ docker_compose_version.stdout }}"
